In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import category_encoders as ce
from kmodes.kmodes import KModes

In [2]:
df=pd.read_csv("dataset/subscriptions_60000_utf8.csv")

/tmp/ipykernel_17520/3637966403.py:1: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("dataset/subscriptions_60000_utf8.csv")

In [3]:
#unique values in 'revenue' for each service
for service in df['service'].unique():
    unique_values = df.loc[df['service'] == service, 'revenue'].unique()
    print(f"Service {service}: {unique_values}")

Service SLYPEE FSC: [1000    0]
Service PLAYZONE: [ 8000     0 12000  6000  4000  2000 22000 10000 14000 30000 24000 58000
 32000 26000 16000 20000 36000 40000 60000 46000 18000 34000]
Service SLYPEE DFS: [   0 1000]
Service CLOUDPLAY: [2000    0 4000]
Service slypee dfs: [1000    0]
Service slypee fsc: [1000    0]
Service GAMESPOT: [    0 10000  4000  2000 14000  8000  6000 12000 64000 20000 24000 16000
 18000 48000 34000 22000 38000 50000 76000 26000]
Service FUN1: [1000]
Service QUIZPRO: [   0 2000]
Service GAMESC LKT: [1000    0]
Service GAZY: [    0 28000 10000 14000 34000]
Service CLOUDPLAY 1: [3000    0]
Service GMSPAZE: [0]
Service GALAYS: [0]
Service gemezz: [     0   7000  29000  25000 117000   5000  20000  10000  17000  43000
  50000   9000  11000  45000  33000  62000  46000  35000   4000  23000
  12000  31000  54000  98000   6000   8000  80000 114000   2000  68000
  18000  13000  77000  37000  67000  34000  51000  53000  22000 103000
  16000 189000  94000  89000  32000  28000 113000  21000  19000  48000
  93000  27000 122000  39000  65000  63000   1000 238000  26000  49000
  38000 135000  24000  59000  14000 124000  88000  44000   3000  76000
  64000  58000  30000 247000  82000  92000  55000  70000 128000  56000
  36000  15000  96000  60000 111000 164000  74000 288000  83000  42000
 148000 130000 120000 251000 116000  52000  66000  84000 100000 102000
 142000 121000  97000 143000 105000  57000  41000  40000 139000 250000
  73000  81000  78000 136000  61000 149000  72000  75000 147000 126000
 167000 150000 173000 141000  47000 119000 108000  91000  79000 129000
  85000 266000 166000 175000  69000 104000  95000 109000 165000 112000
 170000 131000  86000 178000 145000  71000 155000 106000  90000 146000
 169000 174000 161000 125000 312000  99000 138000 201000 231000  87000
 209000 132000 133000 118000 134000 156000 197000 115000 185000 190000
 123000 140000 179000 110000 358000 314000 199000 101000 202000 318000
 216000 309000 176000 153000 286000 323000 225000 154000 158000 181000
 127000 246000 193000 137000  40300    450    100   1500   1700    300
    500   1800   1300   2200     50    600  68750   6250    950    700
  56650    250   7600   4050    750   5450  61100   1250   6350   8400
   2750    900    400   2500   1750  18750    350    550  11750  10200
   8500   1200  92500    200   8550  13700   1050   1650  14650    650
   8450   5050   4500  11850  18600   1450   1150   4850 101250   3300
 138600   4450   7900   2650   9700   6550   8350   2250   2450   4750
   4300   6750    800   3250   4250   8250   7500   3400   3750  81250
    850   2350    150]
Service quizy: [31000 58000  1000     0 30000 25000 14000  8000 59000  3000 53000  2000
  4000 13000  5000  6000 29000 34000 63000 16000 32000 19000 12000 42000
 28000 10000 50000 11000 21000 84000 20000 37000 78000 43000  9000 33000
 15000 39000 27000 24000 48000 54000 23000 77000 65000 64000 38000 36000
 62000 47000 45000 72000 17000  7000 22000 35000 40000 52000 56000 18000
 26000 60000 55000 90000 51000 49000 61000 94000 44000 67000 70000 81000
 41000 69000 66000 46000 87000]
Service slypee: [     0  28000   4000   8000   2000  12000  18000  54000   6000  44000
  78000  32000  16000  30000  34000  14000  10000  20000  24000  56000
  26000  36000  76000 108000 166000  22000  50000  64000  68000  40000
  60000  58000  48000  52000  38000  46000  92000  70000  42000 144000
  80000  86000  72000 102000 150000 100000  82000  98000 176000 110000
 130000  62000  74000 112000 162000 118000  66000 154000 122000 180000
 164000 210000  90000 160000 128000  84000 142000]
Service halogame: [16000  4000     0 20000 12000  1000 11000 18000  7000 28000  6000  3000
 32000 81000 68000 40000  5000 51000 60000 14000 30000 26000 29000 56000
  2000 31000 38000  8000 10000 49000 46000 25000 13000 19000  9000 34000
 78000 21000 36000 35000 45000 27000 43000]
Service goaly: [     0    600    300   6000   6300  22800   2400  27000    900   3300
   7500   3000   1500   3600   1200  18000   2700   1800   3900   6900
   9000   5100   9300   7200   2100   9600  17100   5700  13500  10800
  14400   6600   4500  12900  13200  31200   8400   4200  10500  14100
  28200  21900   8100  10200  23100   5400   4800  14700  29400  21300
  31800  50700   8700  44400  32700  37500  25500  34200  24900  12000
  41400 117600  12300  11400  63600  16800  38700  17700  29700  15900
   7800  21600  15600  11700  18600  12600  16200  15000  22500  11100
  59700  30900  27900  41100  35400  23700  23400  78900  26700  18300
  49200  15300  18900  51600  50100  22200  60000  47700  31500   9900
  13800  38100  24600  19200  24300  33900  61500  27300  20400  36900
  56400  65100 112800  39600  26400  20700  17400  34800  21000  32400
  72900  56100  28800  29100  25200  50400  63900  45300 100500  47100
  28500  27600  42900  94800  33300  39300  30000  60600  48600  25800
  30600  30300  96900  34500  98400  49800  58500  36000  24000  33600
  19800  43800  20100  65400  66300 114000  64200  37800 118800  26100
  90900  78300  69300  16500  48900  36300]
Service linguisto: [    0 80400  9900  2100   900 10500   600 25800  1500 14100  1200 32100
 24600 41700 11700  5400  2400  1800  9300 10800 20400  6000 14400   300
 24000 12000  8100 12300 42300  4200 16500  7800 11400  4500 15600  2700
 24300  4800 13800 23100 19500 30300  5100 61500  3900 54600  3300  7200
  5700 21600 18900  8700 57600 34800  3000  9000  9600 22800 21000 80100
 21300 37500 24900 13200  7500  6900 25200 16200 75900 26400 44700 10200
 75300 14700 15000 44100 15300  8400  6300 29100 59700 65700 39600 16800
 12900 12600 17700 13500 41100  3600 15900 33000 42900  6600 46200]
Service omantel: [ 1500   300     0 40500 11700  3300  3600  7500 31200 60300   900  8700
  5100 19200  5700   600 66600 47700  1800  6900 36600  4800  6600 63600
 20700  9600 14400  5400  3900 61200 10200 10800 21300  9300  4200 14700
  9000 25500 38700 56100  6000  2400 17700 18600  3000  4500  6300 11400
 39000 19800  7800  1200  8100 12600 13800  2100 60600 11100 43200 27600
 12300 24900 45300 16200 12000 60000  2700 49800  9900 22200 13200 40800
 28200 18000 51300 15600]
Service 10291: [  0  10  30  20 100  40 590  60  50 150 110  90 170 640 200  80 120  70
 260 130 140 190 160 380 250]
Service 10292: [ 80   0  20  30  10 160 120  40 100  90 130 150  50  60 140 270 110 170
  70]
Service 9109: [0]
Service GE: [   0    4   56   12 1056   40  172   64   44 2608  112  188   24   16
  168   28   36  336  184   72  128    8]
Service 459509902: [  0  18 114   6  12  36  30  24  42 168 126  54 390  72 174 108  48  60
  66]
Service 459505105: [ 12   0  18   6  42  24  30  36  54  72  60 138]
Service 459505104: [  0  18   6  12  42  30  24  48  54  96  36  66 132]
Service 459505106: [ 0  6 12 18 24 36 30 42 48 60 84]
Service 459509903: [ 0 30  6 24 12 84 42 18 36 48]
Service 459509901: [  0  12  30   6  24  18 138 330  54  66  36  60  42  48]
Service GEE: [0]
Service GED: [  0 124   4 192 112  36  56  40 140 608 280]
Service GEA: [0]
Service GE7: [0]
Service GEF: [   0   56   24  168  308  672   40   20    4   12 1952  112]
Service GE7A: [0]
Service GEC: [0]
Service GEB: [0]
Service GE1: [0]

In [5]:
import pandas as pd
from scipy.stats import f_oneway


top_services = df.groupby('service')['revenue'].nunique().sort_values(ascending=False).head(5).index


df_top = df[df['service'].isin(top_services)]

# Perform ANOVA
f_statistic, p_value = f_oneway(*[df_top['revenue'][df_top['service'] == service] for service in top_services])


print(f'F-statistic: {f_statistic}')
print(f'P-value: {p_value}')

# Resul Intrepretations
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis. There is a significant difference in revenue across different services.")
else:
    print("Fail to reject the null hypothesis. There is no significant difference in revenue across different services.")

F-statistic: 322.814017408725
P-value: 8.750433550066334e-271
Reject the null hypothesis. There is a significant difference in revenue across different services.